// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Uplink$HoustonPocReasonml = require("../uplink/Uplink.bs.js");
var Helpers$HoustonPocReasonml = require("./command_sequence_js_helpers/Helpers.bs.js");

function createCommandSequence(_root, args) {
  var commandSequenceInput = args.sequence;
  var commandSequence = Helpers$HoustonPocReasonml.injectSequenceAndCommandIds(commandSequenceInput);
  var path = "src/command_sequence/" + (commandSequence.id + ".json");
  return Helpers$HoustonPocReasonml.writeCommandSequence(path, commandSequence).then(Helpers$HoustonPocReasonml.readCommandSequence);
}

function uplinkCommandSequence(dep) {
  var uplink = Uplink$HoustonPocReasonml.create(dep);
  return function (_root, args) {
    var path = "src/command_sequence/" + (args.id + ".json");
    return Helpers$HoustonPocReasonml.readCommandSequence(path).then(function (sequence) {
                Uplink$HoustonPocReasonml.start(uplink, sequence);
                return Promise.resolve(true);
              });
  };
}

function resolvers(dep) {
  return {
          createCommandSequence: createCommandSequence,
          uplinkCommandSequence: uplinkCommandSequence(dep)
        };
}

exports.createCommandSequence = createCommandSequence;
exports.uplinkCommandSequence = uplinkCommandSequence;
exports.resolvers = resolvers;
/* Helpers-HoustonPocReasonml Not a pure module */
