// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Helpers$HoustonPocReasonml = require("./command_sequence_js_helpers/Helpers.bs.js");

var resolvers = {
  findCommandSequence: (function (_root, args) {
      return Helpers$HoustonPocReasonml.readCommandSequence("src/command_sequence/" + (args.id + ".json"));
    })
};

exports.resolvers = resolvers;
/* Helpers-HoustonPocReasonml Not a pure module */
