// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function resolvers(pubsub) {
  return {
          state: {
            subscribe: (function (param) {
                return pubsub.asyncIterator("STATE");
              })
          }
        };
}

exports.resolvers = resolvers;
/* No side effect */
