// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Helpers = require("./helpers");

function readCommandSequence(prim) {
  return Helpers.readJsonFile(prim);
}

function writeCommandSequence(prim, prim$1) {
  return Helpers.writeJsonFile(prim, prim$1);
}

function injectSequenceAndCommandIds(prim) {
  return Helpers.injectSequenceAndCommandIds(prim);
}

exports.readCommandSequence = readCommandSequence;
exports.writeCommandSequence = writeCommandSequence;
exports.injectSequenceAndCommandIds = injectSequenceAndCommandIds;
/* ./helpers Not a pure module */
