// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var initialUplinkState = {
  sequenceId: undefined,
  pending: /* [] */0,
  unresolved: /* [] */0,
  successful: /* [] */0,
  failed: /* [] */0,
  inProgress: false
};

var initialState = {
  uplink: initialUplinkState
};

function mapToSchemaState(param) {
  var uplink = param.uplink;
  return {
          state: {
            uplink: {
              sequenceId: Js_null_undefined.fromOption(uplink.sequenceId),
              pending: $$Array.of_list(uplink.pending),
              unresolved: $$Array.of_list(uplink.unresolved),
              successful: $$Array.of_list(uplink.successful),
              failed: $$Array.of_list(uplink.failed),
              inProgress: uplink.inProgress
            }
          }
        };
}

exports.initialUplinkState = initialUplinkState;
exports.initialState = initialState;
exports.mapToSchemaState = mapToSchemaState;
/* No side effect */
